### ISSUE TITLE
How to set data type float

### ISSUE THREAD

**Issue by fideltak** [googleapis/gnostic-grpc#25]
I'm not sure the way to set float as data type.  
My OAS3 yaml is defined some prameters as float.  

```
        location:
          type: object
          properties:
            longitude:
              type: number
              format: float
            latitude:
              type: number
              format: float
              example: 139.599194
```
However when creating proto file by *gnostic*, they are turned to int.  

```
message Location {
  int32 longitude = 1;

  int32 latitude = 2;
}
```

Please give some advices...
